<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="120847" started-at="2018-05-07T20:47:04Z" finished-at="2018-05-07T20:49:05Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="120847" started-at="2018-05-07T20:47:04Z" finished-at="2018-05-07T20:49:05Z">
      <class name="tests.TestEtna">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.TestEtna@14acaea5]" name="setUp" is-config="true" duration-ms="18609" started-at="2018-05-07T17:47:04Z" finished-at="2018-05-07T17:47:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testHomePage()[pri:1, instance:tests.TestEtna@14acaea5]" name="testHomePage" duration-ms="5181" started-at="2018-05-07T17:47:22Z" finished-at="2018-05-07T17:47:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePage -->
        <test-method status="PASS" signature="testListaPresente()[pri:2, instance:tests.TestEtna@14acaea5]" name="testListaPresente" duration-ms="10592" started-at="2018-05-07T17:47:28Z" finished-at="2018-05-07T17:47:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListaPresente -->
        <test-method status="PASS" signature="testNossasLojas()[pri:3, instance:tests.TestEtna@14acaea5]" name="testNossasLojas" duration-ms="7454" started-at="2018-05-07T17:47:38Z" finished-at="2018-05-07T17:47:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNossasLojas -->
        <test-method status="PASS" signature="testLogin()[pri:4, instance:tests.TestEtna@14acaea5]" name="testLogin" duration-ms="12920" started-at="2018-05-07T17:47:46Z" finished-at="2018-05-07T17:47:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="FAIL" signature="testCarrinho()[pri:5, instance:tests.TestEtna@14acaea5]" name="testCarrinho" duration-ms="49912" started-at="2018-05-07T17:47:59Z" finished-at="2018-05-07T17:48:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at tests.TestEtna.testCarrinho(TestEtna.java:384)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCarrinho -->
        <test-method status="PASS" signature="testLogOut()[pri:20, instance:tests.TestEtna@14acaea5]" name="testLogOut" duration-ms="15345" started-at="2018-05-07T17:48:48Z" finished-at="2018-05-07T17:49:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogOut -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.TestEtna@14acaea5]" name="tearDown" is-config="true" duration-ms="764" started-at="2018-05-07T17:49:04Z" finished-at="2018-05-07T17:49:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.TestEtna -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
