<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="6" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="98894" started-at="2018-05-07T18:08:38Z" finished-at="2018-05-07T18:10:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="98894" started-at="2018-05-07T18:08:38Z" finished-at="2018-05-07T18:10:17Z">
      <class name="tests.testEtna">
        <test-method status="PASS" signature="setUp()[pri:0, instance:tests.testEtna@14acaea5]" name="setUp" is-config="true" duration-ms="24164" started-at="2018-05-07T15:08:38Z" finished-at="2018-05-07T15:09:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testHomePage()[pri:1, instance:tests.testEtna@14acaea5]" name="testHomePage" duration-ms="5035" started-at="2018-05-07T15:09:02Z" finished-at="2018-05-07T15:09:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testHomePage -->
        <test-method status="PASS" signature="testListaPresente()[pri:2, instance:tests.testEtna@14acaea5]" name="testListaPresente" duration-ms="8672" started-at="2018-05-07T15:09:07Z" finished-at="2018-05-07T15:09:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testListaPresente -->
        <test-method status="PASS" signature="testNossasLojas()[pri:3, instance:tests.testEtna@14acaea5]" name="testNossasLojas" duration-ms="6632" started-at="2018-05-07T15:09:16Z" finished-at="2018-05-07T15:09:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testNossasLojas -->
        <test-method status="PASS" signature="testLogin()[pri:4, instance:tests.testEtna@14acaea5]" name="testLogin" duration-ms="13123" started-at="2018-05-07T15:09:22Z" finished-at="2018-05-07T15:09:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="FAIL" signature="testCarrinho()[pri:5, instance:tests.testEtna@14acaea5]" name="testCarrinho" duration-ms="25552" started-at="2018-05-07T15:09:35Z" finished-at="2018-05-07T15:10:01Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertTrue(Assert.java:44)at org.testng.Assert.assertTrue(Assert.java:54)at tests.testEtna.testCarrinho(testEtna.java:384)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCarrinho -->
        <test-method status="PASS" signature="testLogOut()[pri:20, instance:tests.testEtna@14acaea5]" name="testLogOut" duration-ms="14693" started-at="2018-05-07T15:10:01Z" finished-at="2018-05-07T15:10:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogOut -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:tests.testEtna@14acaea5]" name="tearDown" is-config="true" duration-ms="917" started-at="2018-05-07T15:10:16Z" finished-at="2018-05-07T15:10:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.testEtna -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
